### ISSUE TITLE
Add image assets for BOTW foods

### ISSUE THREAD

**Issue by apederson21** [hanalways/link-make-me-a-sandwich#2]

**Comment by hanalways** [comment]
We might be able to just leverage open source apis at first?

[Hyrule Compendium API](https://github.com/gadhagod/Hyrule-Compendium-API)

**Comment by apederson21** [comment]
Yea this is great, fruits and veggies are [here](https://botw-compendium.herokuapp.com/api/v3/compendium/category/materials) and meats can be found [here](https://botw-compendium.herokuapp.com/api/v3/compendium/category/creatures). Looks like we'll need to do some parsing, but maybe this work becomes: 
1. fetch foods via H.C. API
2. parse data and categorize into state - we'll want to normalize everything in our state, maybe just a unique across the two [provided schemas](https://gadhagod.github.io/Hyrule-Compendium-API/#/compendium-api?id=entry-schemas)

**Comment by apederson21** [comment]
Please grant push access to the repo and I'll take this!

**Comment by hanalways** [comment]
I set you a link to be a collaborator, but not sure what access that gets you. Let me see if I can hook you up :D
